pool:
  vmImage: "ubuntu-16.04"

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    repository: 'ss13-scp13'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    command: 'logout'