pool:
  vmImage: 'ubuntu-18.04'

variables:
  dockerId: "looreydev"
  imageName: "ss13-scp13"

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)