pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'quay.io/repository/looreydev/'

steps:
- task: Docker@0
  displayName: 'build'
  inputs:
    imageName: '$(imageName)'
    buildArguments: BUILD_ARGS=-Icustom-items/inc.dm

- task: Docker@1
  displayName: 'registry login'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'ss13-scp13'
    command: login

- task: Docker@1
  displayName: 'push'
  inputs:
    command: 'Push an Image'
    imageName: '$(imageName)'
