pool:
  vmImage: "ubuntu-16.04"

steps:
- script: docker login -u ss13scp13 -p $(dockerPassword)
  displayName: "login to docker"

- script: |
    apt-get update
    apt-get upgrade
    docker build -f Dockerfile -t ss13scp13/ss13-scp13 .
  displayName: "build docker image"

- script: docker push ss13scp13/ss13-scp13
  displayName: "push to docker"

- script: docker logout
  displayName: "logout"

- task: ado-discord-webhook@1
  displayName: "report status to discord"
  inputs:
    channelId: '$(discordChanId)'
    webhookKey: '$(discordWebhookUri)'
    name: 'Azure'
    avatar: 'https://avatars.slack-edge.com/2019-01-17/528389819366_e7a0672f0480b3e98d21_512.png'
    messageType: 'embeds'