pool:
  vmImage: "ubuntu 18.04"

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    repository: 'ss13-scp13'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    repository: 'ss13-scp13'
    command: 'push'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    command: 'logout'