pool:
  vmImage: "ubuntu-16.04"

steps:

- script: docker login docker.io -u $(dockerId) -p $(dockerPassword)
  displayName: "login to docker.io"

- task: Docker@2
  displayName: "build container"
  inputs:
    containerRegistry: 'docker'
    repository: '$(dockerRepo)'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- script: docker push $(dockerId)/$(dockerRepo):$(dockerTag)
  displayName: "push container"

- script: docker logout
  displayName: "log out of docker"