pool:
  vmImage: "ubuntu-16.04"

steps:

- script: docker login docker.io -u looreydev -p $(dockerPassword)
  displayName: "login to docker.io"

- task: Docker@2
  displayName: "pushing and building"
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    repository: 'ss13-scp13'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: "log out of docker.io"
  inputs:
    containerRegistry: 'Docker Hub - Looreydev'
    command: 'logout'